#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
    /usr/bin/update_msfs_ipset.sh
    iptables -t mangle -A PREROUTING -m set --match-set vpn_domains dst -j MARK --set-mark 0x1
}

stop() {
    iptables -t mangle -D PREROUTING -m set --match-set vpn_domains dst -j MARK --set-mark 0x1 2>/dev/null
}
